#!/usr/bin/env python3
"""V5 Behavior Contract — the single source of truth for the pipeline.

Every stage reads this contract. No stage guesses.

The contract is generated by Layer 3 (semantic filtering) and consumed by:
  - Blender prep (set origins, remove faces, fix materials)
  - PhysX stage (create joints, collision, mass)
  - Judge D (validate at every stage)
  - Layer 4 (robot capability check)
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
import json


# ═══════════════════════════════════════════════════════════════════════════════
# 16 BEHAVIORS
# ═══════════════════════════════════════════════════════════════════════════════

BEHAVIORS = [
    # Original 8
    "rotational",           # doors, knobs, valves, hinges
    "linear",               # drawers, sliders, buttons
    "grasping",             # any graspable object
    "insertion",            # pegs, plugs, keys, screws
    "deformation",          # cloth, rubber, foam, wire
    "contact",              # buttons, switches, taps
    "sequential",           # multi-step (unlock + open)
    "dynamic",              # throwing, catching, bouncing
    # Extended 8
    "sliding_friction",     # pushing objects across surfaces
    "wiping_sweeping",      # repetitive surface cleaning
    "twisting_torque",      # jar lids, bolts while grasped
    "stacking_placement",   # precise stable placement
    "compliant_force",      # polishing, sanding, scrubbing
    "impact_striking",      # hammering, bell striking
    "pulling_tension",      # extracting objects (drawers, pegs)
    "rolling",              # round objects, v = ω × r
]

# ═══════════════════════════════════════════════════════════════════════════════
# 15 SEMANTIC CONSTRAINT DOMAINS
# ═══════════════════════════════════════════════════════════════════════════════

CONSTRAINT_DOMAINS = [
    "directional",          # 1. Motion must match intended direction
    "range_limits",         # 2. Motion within physical bounds
    "pivot_placement",      # 3. Rotation around correct pivot
    "clearance",            # 4. No self-collision
    "sequential",           # 5. Actions may have prerequisites
    "force_torque",         # 6. Realistic force/torque
    "contact_friction",     # 7. Proper surface contact
    "symmetry",             # 8. Symmetric or asymmetric
    "material",             # 9. Material affects behavior
    "internal_volume",      # 10. Internal geometry restricts motion
    "kinematic_chain",      # 11. Respects mechanical structure
    "energy",               # 12. Appropriate energy source
    "feedback",             # 13. May require sensors
    "safety",               # 14. Safety limits
    "aesthetic",            # 15. Affects appearance
]


# ═══════════════════════════════════════════════════════════════════════════════
# CONSTRAINT CHECK RESULT
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ConstraintCheck:
    """Result of checking one constraint domain for one behavior."""
    domain: str                     # which of 15 domains
    applies: bool                   # does this domain apply to this behavior?
    satisfied: bool = True          # if applies, is it satisfied?
    value: Optional[str] = None     # the specific value/parameter
    reason: str = ""                # why satisfied or violated


# ═══════════════════════════════════════════════════════════════════════════════
# BEHAVIOR SPEC — one valid behavior for one part
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class BehaviorSpec:
    """Specification for one valid behavior of one part."""
    behavior_type: str              # one of 16 behaviors
    is_valid: bool                  # did it pass semantic filtering?

    # Joint parameters (from semantic filtering)
    joint_type: Optional[str] = None        # "revolute", "prismatic", "fixed", None
    joint_axis: Optional[str] = None        # "X", "Y", "Z"
    joint_limits_deg: Optional[Tuple[float, float]] = None   # for revolute
    joint_limits_m: Optional[Tuple[float, float]] = None     # for prismatic
    damping: float = 0.0
    stiffness: float = 0.0
    force_nm: float = 0.0                   # force or torque required

    # Pivot / anchor
    pivot_position: Optional[Tuple[float, float, float]] = None  # world coords
    pivot_description: str = ""     # e.g., "bottom edge hinge"

    # Collision
    collision_type: str = "none"    # "convexHull", "boundingCube", "none"
    collision_enabled_between_bodies: bool = False

    # Constraint check results
    constraint_checks: List[ConstraintCheck] = field(default_factory=list)

    # If invalid, why
    violation_reasons: List[str] = field(default_factory=list)


# ═══════════════════════════════════════════════════════════════════════════════
# PART CONTRACT — all behaviors for one part
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class PartContract:
    """Behavior contract for one part of the object."""
    name: str                       # e.g., "door_lower"
    part_type: str                  # e.g., "oven_door", "drawer", "knob"
    is_static: bool = False         # does it move?

    # From Layer 1: mechanical properties
    vertices: int = 0
    faces: int = 0
    bbox_min: Tuple[float, float, float] = (0, 0, 0)
    bbox_max: Tuple[float, float, float] = (0, 0, 0)
    dims_mm: Tuple[float, float, float] = (0, 0, 0)
    origin: Tuple[float, float, float] = (0, 0, 0)
    materials: List[str] = field(default_factory=list)
    mass_kg: float = 1.0

    # From Layer 2: plausible behaviors (all 16 checked)
    plausible_behaviors: List[str] = field(default_factory=list)

    # From Layer 3: the primary valid behavior (filtered)
    primary_behavior: Optional[BehaviorSpec] = None

    # From Layer 3: all valid behaviors
    valid_behaviors: List[BehaviorSpec] = field(default_factory=list)

    # From Layer 3: all invalid behaviors with reasons
    invalid_behaviors: List[BehaviorSpec] = field(default_factory=list)

    # Blender prep actions needed
    blender_actions: List[str] = field(default_factory=list)
    # e.g., ["set_origin_to_hinge_edge", "remove_cavity_face", "assign_material"]

    # Parent link (for articulation)
    parent_part: Optional[str] = None       # e.g., "oven_chassis"
    joint_local_pos0: Optional[Tuple[float, float, float]] = None  # on parent
    joint_local_pos1: Tuple[float, float, float] = (0, 0, 0)      # on this part
    spatial_children: List[str] = field(default_factory=list)  # parts spatially inside this one


# ═══════════════════════════════════════════════════════════════════════════════
# FULL BEHAVIOR CONTRACT — the whole object
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class BehaviorContract:
    """Complete behavior contract for the entire object.

    This is the SINGLE SOURCE OF TRUTH for the pipeline.
    Every downstream stage reads this and does exactly what it says.
    """
    object_name: str                # e.g., "double_wall_oven"
    object_type: str                # e.g., "appliance"
    source_file: str                # e.g., "built_in_double_oven_final.obj"

    # All parts
    parts: List[PartContract] = field(default_factory=list)

    # Root body (for articulation)
    root_part: Optional[str] = None     # name of the static root

    # Overall
    overall_dims_mm: Tuple[float, float, float] = (0, 0, 0)

    # Pipeline metadata
    layer1_complete: bool = False
    layer2_complete: bool = False
    layer3_complete: bool = False
    blender_complete: bool = False
    physx_complete: bool = False
    validated: bool = False
    containment_tree: Dict[str, List[str]] = field(default_factory=dict)  # parent → [children] from geometry

    def get_part(self, name: str) -> Optional[PartContract]:
        for p in self.parts:
            if p.name == name:
                return p
        return None

    def to_json(self) -> str:
        """Serialize to JSON for passing between stages."""
        def _serialize(obj):
            if hasattr(obj, '__dataclass_fields__'):
                return {k: _serialize(v) for k, v in obj.__dict__.items()}
            elif isinstance(obj, list):
                return [_serialize(i) for i in obj]
            elif isinstance(obj, tuple):
                return list(obj)
            return obj
        return json.dumps(_serialize(self), indent=2)

    @classmethod
    def from_json(cls, text: str) -> 'BehaviorContract':
        """Deserialize from JSON."""
        data = json.loads(text)
        contract = cls(
            object_name=data["object_name"],
            object_type=data["object_type"],
            source_file=data["source_file"],
        )
        contract.root_part = data.get("root_part")
        contract.overall_dims_mm = tuple(data.get("overall_dims_mm", (0, 0, 0)))

        for pd in data.get("parts", []):
            part = PartContract(
                name=pd["name"],
                part_type=pd["part_type"],
                is_static=pd.get("is_static", False),
                vertices=pd.get("vertices", 0),
                faces=pd.get("faces", 0),
                mass_kg=pd.get("mass_kg", 1.0),
                materials=pd.get("materials", []),
                parent_part=pd.get("parent_part"),
            )
            if pd.get("bbox_min"):
                part.bbox_min = tuple(pd["bbox_min"])
            if pd.get("bbox_max"):
                part.bbox_max = tuple(pd["bbox_max"])
            if pd.get("dims_mm"):
                part.dims_mm = tuple(pd["dims_mm"])
            if pd.get("origin"):
                part.origin = tuple(pd["origin"])
            if pd.get("joint_local_pos0"):
                part.joint_local_pos0 = tuple(pd["joint_local_pos0"])
            if pd.get("joint_local_pos1"):
                part.joint_local_pos1 = tuple(pd["joint_local_pos1"])

            part.plausible_behaviors = pd.get("plausible_behaviors", [])
            part.blender_actions = pd.get("blender_actions", [])
            part.spatial_children = pd.get("spatial_children", [])

            # Reconstruct behaviors
            for bd in pd.get("valid_behaviors", []):
                spec = _dict_to_behavior_spec(bd)
                part.valid_behaviors.append(spec)
            for bd in pd.get("invalid_behaviors", []):
                spec = _dict_to_behavior_spec(bd)
                part.invalid_behaviors.append(spec)

            if pd.get("primary_behavior"):
                part.primary_behavior = _dict_to_behavior_spec(pd["primary_behavior"])

            contract.parts.append(part)

        for k in ["layer1_complete", "layer2_complete", "layer3_complete",
                   "blender_complete", "physx_complete", "validated"]:
            setattr(contract, k, data.get(k, False))

        contract.containment_tree = data.get("containment_tree", {})

        return contract


def _dict_to_behavior_spec(d: dict) -> BehaviorSpec:
    spec = BehaviorSpec(
        behavior_type=d.get("behavior_type", ""),
        is_valid=d.get("is_valid", False),
        joint_type=d.get("joint_type"),
        joint_axis=d.get("joint_axis"),
        damping=d.get("damping", 0),
        stiffness=d.get("stiffness", 0),
        force_nm=d.get("force_nm", 0),
        pivot_description=d.get("pivot_description", ""),
        collision_type=d.get("collision_type", "none"),
        collision_enabled_between_bodies=d.get("collision_enabled_between_bodies", False),
        violation_reasons=d.get("violation_reasons", []),
    )
    if d.get("joint_limits_deg"):
        spec.joint_limits_deg = tuple(d["joint_limits_deg"])
    if d.get("joint_limits_m"):
        spec.joint_limits_m = tuple(d["joint_limits_m"])
    if d.get("pivot_position"):
        spec.pivot_position = tuple(d["pivot_position"])
    for cd in d.get("constraint_checks", []):
        spec.constraint_checks.append(ConstraintCheck(
            domain=cd["domain"],
            applies=cd["applies"],
            satisfied=cd.get("satisfied", True),
            value=cd.get("value"),
            reason=cd.get("reason", ""),
        ))
    return spec
